apiVersion: v1
kind: Service
metadata:
  name: barramento-de-eventos-service
spec:
  selector:
    app: barramento-de-eventos
  ports:
    - protocol: "TCP"
      port: 10000
      targetPort: 10000
  type: ClusterIP
