apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulta
  template:
    metadata:
      labels:
        app: consulta
    spec:
      containers:
      - name: consulta
        image: consulta
        ports:
        - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: consulta-service
spec:
  selector:
    app: consulta
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6000
