apiVersion: apps/v1
kind: Deployment
metadata:
  name: observacoes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observacoes
  template:
    metadata:
      labels:
        app: observacoes
    spec:
      containers:
      - name: observacoes
        image: observacoes
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: observacoes-service
spec:
  selector:
    app: observacoes
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
